### ISSUE TITLE
Golint panic due to latest changes

### ISSUE THREAD

**Issue by abronan** [golang/lint#116]
It seems to be related to the latest commit (23587b4bcbd24e87e3de4d19dfadb947df6fc2ed).

Output:

```
$ fgt golint -min_confidence=0.9 ./...
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x20 pc=0x47041d]
goroutine 16 [running]:
runtime.panic(0x662f80, 0x7e7813)
	/usr/local/go/src/pkg/runtime/panic.c:279 +0xf5
github.com/golang/lint.func·010(0x7fa1aa342f30, 0xc20806c1c0, 0x64e301)
	/home/travis/gopath/src/github.com/docker/swarm/Godeps/_workspace/src/github.com/golang/lint/lint.go:1050 +0x1cd
github.com/golang/lint.walker.Visit(0xc20814bdd0, 0x7fa1aa342f30, 0xc20806c1c0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/docker/swarm/Godeps/_workspace/src/github.com/golang/lint/lint.go:1412 +0x48
go/ast.Walk(0x7fa1aa342de8, 0xc20814bdd0, 0x7fa1aa342f30, 0xc20806c1c0)
	/usr/local/go/src/pkg/go/ast/walk.go:52 +0x58
go/ast.Walk(0x7fa1aa342de8, 0xc20814bdd0, 0x7fa1aa3431a0, 0xc20809b6b0)
	/usr/local/go/src/pkg/go/ast/walk.go:196 +0x428d
go/ast.walkStmtList(0x7fa1aa342de8, 0xc20814bdd0, 0xc20809b6e0, 0x1, 0x1)
	/usr/local/go/src/pkg/go/ast/walk.go:32 +0xd1
go/ast.Walk(0x7fa1aa342de8, 0xc20814bdd0, 0x7fa1aa342b90, 0xc20800f110)
	/usr/local/go/src/pkg/go/ast/walk.go:224 +0x41e7
go/ast.Walk(0x7fa1aa342de8, 0xc20814bdd0, 0x7fa1aa342b60, 0xc20806c200)
	/usr/local/go/src/pkg/go/ast/walk.go:231 +0x4434
go/ast.walkStmtList(0x7fa1aa342de8, 0xc20814bdd0, 0xc20806c240, 0x3, 0x4)
	/usr/local/go/src/pkg/go/ast/walk.go:32 +0xd1
go/ast.Walk(0x7fa1aa342de8, 0xc20814bdd0, 0x7fa1aa342b90, 0xc20800f140)
	/usr/local/go/src/pkg/go/ast/walk.go:224 +0x41e7
go/ast.Walk(0x7fa1aa342de8, 0xc20814bdd0, 0x7fa1aa342bf0, 0xc20806c280)
	/usr/local/go/src/pkg/go/ast/walk.go:275 +0x1389
go/ast.walkStmtList(0x7fa1aa342de8, 0xc20814bdd0, 0xc20805e900, 0xb, 0x10)
	/usr/local/go/src/pkg/go/ast/walk.go:32 +0xd1
go/ast.Walk(0x7fa1aa342de8, 0xc20814bdd0, 0x7fa1aa342b90, 0xc20800f170)
	/usr/local/go/src/pkg/go/ast/walk.go:224 +0x41e7
go/ast.Walk(0x7fa1aa342de8, 0xc20814bdd0, 0x7fa1aa342ea0, 0xc20800f1a0)
	/usr/local/go/src/pkg/go/ast/walk.go:342 +0xccb
go/ast.walkDeclList(0x7fa1aa342de8, 0xc20814bdd0, 0xc20806c2c0, 0x3, 0x4)
	/usr/local/go/src/pkg/go/ast/walk.go:38 +0xd1
go/ast.Walk(0x7fa1aa342de8, 0xc20814bdd0, 0x7fa1aa33e300, 0xc208050b80)
	/usr/local/go/src/pkg/go/ast/walk.go:351 +0x2cb6
github.com/golang/lint.(*file).walk(0xc20806c300, 0xc20814bdd0)
	/home/travis/gopath/src/github.com/docker/swarm/Godeps/_workspace/src/github.com/golang/lint/lint.go:1388 +0x82
github.com/golang/lint.(*file).lintErrorf(0xc20806c300)
	/home/travis/gopath/src/github.com/docker/swarm/Godeps/_workspace/src/github.com/golang/lint/lint.go:1065 +0x6c
github.com/golang/lint.(*file).lint(0xc20806c300)
	/home/travis/gopath/src/github.com/docker/swarm/Godeps/_workspace/src/github.com/golang/lint/lint.go:177 +0x97
github.com/golang/lint.(*pkg).lint(0xc20807b630, 0x0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/docker/swarm/Godeps/_workspace/src/github.com/golang/lint/lint.go:149 +0xfc
github.com/golang/lint.(*Linter).LintFiles(0xc20815da60, 0xc208070060, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/docker/swarm/Godeps/_workspace/src/github.com/golang/lint/lint.go:106 +0x43a
main.lintFiles(0xc2080525a0, 0x6, 0xa)
	/home/travis/gopath/src/github.com/docker/swarm/Godeps/_workspace/src/github.com/golang/lint/golint/golint.go:83 +0x235
main.lintImportedPackage(0xc208065500, 0x0, 0x0)
	/home/travis/gopath/src/github.com/docker/swarm/Godeps/_workspace/src/github.com/golang/lint/golint/golint.go:125 +0x490
main.lintDir(0xc20803679b, 0x3)
	/home/travis/gopath/src/github.com/docker/swarm/Godeps/_workspace/src/github.com/golang/lint/golint/golint.go:97 +0x66
main.main()
	/home/travis/gopath/src/github.com/docker/swarm/Godeps/_workspace/src/github.com/golang/lint/golint/golint.go:45 +0x24d
goroutine 19 [finalizer wait]:
runtime.park(0x418040, 0x7ec070, 0x7eabc9)
	/usr/local/go/src/pkg/runtime/proc.c:1369 +0x89
runtime.parkunlock(0x7ec070, 0x7eabc9)
	/usr/local/go/src/pkg/runtime/proc.c:1385 +0x3b
runfinq()
	/usr/local/go/src/pkg/runtime/mgc0.c:2644 +0xcf
runtime.goexit()
	/usr/local/go/src/pkg/runtime/proc.c:1445
error running command: exit status 2
The command "fgt golint -min_confidence=0.9 ./..." exited with 1.
```

Source: https://travis-ci.org/docker/swarm/builds/57624740

**Comment by pguelpa** [comment]
:+1: - we're seeing this on our repository as well

**Comment by pguelpa** [comment]
To add a little more detail, we only seem to see this while running our tests inside the `google/golang:1.3`

**Comment by cmdrkeene** [comment]
:+1: seeing this as well

**Comment by abronan** [comment]
@pguelpa Yes, it seems to be our case as well.
