### ISSUE TITLE
Panic when running on method with missing receiver

### ISSUE THREAD

**Issue by dominikh** [golang/lint#134]
Input:

```go
package main

func () Method() {}
```

go build:

```
./foo.go:3: method has no receiver
```

go lint:

```
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/golang/lint.receiverType(0xc20803ad50, 0x0, 0x0)
        /home/dominikh/prj/go/src/github.com/golang/lint/lint.go:1398 +0x344
github.com/golang/lint.func·002(0x7f96f166a2c8, 0xc20803ad50, 0x0)
        /home/dominikh/prj/go/src/github.com/golang/lint/lint.go:319 +0x86
github.com/golang/lint.walker.Visit(0xc20800a5e0, 0x7f96f166a2c8, 0xc20803ad50, 0x0, 0x0)
        /home/dominikh/prj/go/src/github.com/golang/lint/lint.go:1432 +0x49
go/ast.Walk(0x7f96f166a270, 0xc20800a5e0, 0x7f96f166a2c8, 0xc20803ad50)
        /usr/lib/go/src/go/ast/walk.go:52 +0x59
go/ast.walkDeclList(0x7f96f166a270, 0xc20800a5e0, 0xc208030720, 0x1, 0x1)
        /usr/lib/go/src/go/ast/walk.go:38 +0xd4
go/ast.Walk(0x7f96f166a270, 0xc20800a5e0, 0x7f96f166a0d8, 0xc20806e380)
        /usr/lib/go/src/go/ast/walk.go:353 +0x2df1
github.com/golang/lint.(*file).walk(0xc2080323c0, 0xc20800a5e0)
        /home/dominikh/prj/go/src/github.com/golang/lint/lint.go:1408 +0x83
github.com/golang/lint.(*pkg).scanSortable(0xc208037310)
        /home/dominikh/prj/go/src/github.com/golang/lint/lint.go:324 +0x269
github.com/golang/lint.(*pkg).lint(0xc208037310, 0x0, 0x0, 0x0)
        /home/dominikh/prj/go/src/github.com/golang/lint/lint.go:149 +0x82
github.com/golang/lint.(*Linter).LintFiles(0xc20802bc18, 0xc20803aba0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/dominikh/prj/go/src/github.com/golang/lint/lint.go:110 +0x531
main.lintFiles(0xc20802bf18, 0x1, 0x1)
        /home/dominikh/prj/go/src/github.com/golang/lint/golint/golint.go:83 +0x268
main.main()
        /home/dominikh/prj/go/src/github.com/golang/lint/golint/golint.go:50 +0x367

```

I'm not sure if the bug is in golint, or in the parser.

**Comment by dsymonds** [comment]
I'm a little surprised that the `go/parser` package is accepting that, so I'm not surprised that golint is misbehaving on it. I'm not sure it's worth the time to harden golint against all kinds of AST malformations, so consider filing this at https://golang.org/issue/new as a bug against the `go/parser` package.

**Comment by dominikh** [comment]
Will do. lint also isn't the only program failing on this input. It really should be an upstream issue.

**Comment by dominikh** [comment]
@dsymonds According to https://github.com/golang/go/issues/11271 it's actually the responsibility of the client to check for such abnormalities. Whether you think it's worth it or not is up to you, but `go/parser` doesn't seem to be the right place for the fix.

**Comment by dsymonds** [comment]
It should be easy enough to make golint cope a bit more gracefully.
