### ISSUE TITLE
golint currently panics when run using golang installed from master

### ISSUE THREAD

**Issue by wolfeidau** [golang/lint#207]
The environment.

```
$ go version
go version devel +0b6e5e3 Sun May 8 05:34:56 2016 +0000 darwin/amd64
```

```
golang.org/x/tools](master)$ git log 
commit 2c200eec40d70d74e01852aad22cf6637e8f8f3d
```

Simple test case is running golint against the golint sources.

```
golint](master)$ golint ./...
panic: runtime error: index out of range [recovered]
	panic: runtime error: index out of range

goroutine 1 [running]:
panic(0x1fade0, 0xc4200100f0)
	/usr/local/Cellar/go/HEAD/libexec/src/runtime/panic.go:500 +0x18c
go/types.(*Checker).handleBailout(0xc4200c6380, 0xc4200bd640)
	/usr/local/Cellar/go/HEAD/libexec/src/go/types/check.go:213 +0x95
panic(0x1fade0, 0xc4200100f0)
	/usr/local/Cellar/go/HEAD/libexec/src/runtime/panic.go:458 +0x226
golang.org/x/tools/go/gcimporter15.(*importer).string(0xc4200b0180, 0xc4201af563, 0xb77e)
	/Users/markw/Code/go/src/golang.org/x/tools/go/gcimporter15/bimport.go:625 +0x29b
golang.org/x/tools/go/gcimporter15.BImportData(0xc4201b80f0, 0xc4201dc000, 0x14682, 0x1fe00, 0xc4200ec7e7, 0x5, 0x0, 0x5, 0x3ff0f0, 0x90b80)
	/Users/markw/Code/go/src/golang.org/x/tools/go/gcimporter15/bimport.go:70 +0x153
golang.org/x/tools/go/gcimporter15.Import(0xc4201b80f0, 0xc4200ec7e7, 0x5, 0x22de5c, 0x1, 0x0, 0x0, 0x0)
	/Users/markw/Code/go/src/golang.org/x/tools/go/gcimporter15/gcimporter.go:177 +0x527
github.com/golang/lint.importer.ImportFrom(0x24c2b0, 0xc4201b80f0, 0xc4200ec7e7, 0x5, 0x22de5c, 0x1, 0x0, 0x20d420, 0x31c001, 0x3ff0f0)
	/Users/markw/Code/go/src/github.com/golang/lint/lint16.go:16 +0x4e
github.com/golang/lint.(*importer).ImportFrom(0xc4201af470, 0xc4200ec7e7, 0x5, 0x22de5c, 0x1, 0x0, 0x0, 0x1, 0x1)
	<autogenerated>:5 +0x86
go/types.(*Checker).collectObjects(0xc4200c6380)
	/usr/local/Cellar/go/HEAD/libexec/src/go/types/resolver.go:191 +0x7c5
go/types.(*Checker).checkFiles(0xc4200c6380, 0xc4201b6760, 0x3, 0x4, 0x0, 0x0)
	/usr/local/Cellar/go/HEAD/libexec/src/go/types/check.go:225 +0xa0
go/types.(*Checker).Files(0xc4200c6380, 0xc4201b6760, 0x3, 0x4, 0xc4201b81e0, 0xc4200bd788)
	/usr/local/Cellar/go/HEAD/libexec/src/go/types/check.go:218 +0x3f
go/types.(*Config).Check(0xc4201ba080, 0xc42019e498, 0x4, 0xc4200f4580, 0xc4201b6760, 0x3, 0x4, 0xc4201ad090, 0x0, 0xc420015540, ...)
	/usr/local/Cellar/go/HEAD/libexec/src/go/types/api.go:344 +0x184
github.com/golang/lint.(*pkg).typeCheck(0xc420015810, 0x3a0000000024c208, 0x8)
	/Users/markw/Code/go/src/github.com/golang/lint/lint.go:274 +0x3c9
github.com/golang/lint.(*pkg).lint(0xc420015810, 0xc4200f8420, 0xc4200bd948, 0xc4200bd940)
	/Users/markw/Code/go/src/github.com/golang/lint/lint.go:130 +0x30
github.com/golang/lint.(*Linter).LintFiles(0xc4200bda78, 0xc4200bdb18, 0xc4200bdad0, 0xc4200bdae0, 0x1fb7, 0x0, 0x0)
	/Users/markw/Code/go/src/github.com/golang/lint/lint.go:110 +0x68f
main.lintFiles(0xc4200f4540, 0x3, 0x4)
	/Users/markw/Code/go/src/github.com/golang/lint/golint/golint.go:92 +0x208
main.lintImportedPackage(0xc4200dae00, 0x0, 0x0)
	/Users/markw/Code/go/src/github.com/golang/lint/golint/golint.go:136 +0x357
main.lintDir(0xc4200109e3, 0x3)
	/Users/markw/Code/go/src/github.com/golang/lint/golint/golint.go:107 +0x56
main.main()
	/Users/markw/Code/go/src/github.com/golang/lint/golint/golint.go:49 +0x371
```

After digging into the issue I traced it back to https://github.com/golang/tools/commit/764c4ccf448e9568efd90fa837d6c38ee64252e9#diff-f9250dbc13598f665f314ef639530c96

If I checkout the commit before this one, the software builds and runs fine, specifically https://github.com/golang/tools/commit/5da1e91fb2cc877989e7c73748b505a0612956f2#diff-f9250dbc13598f665f314ef639530c96 and earlier doesn't exhibit this error.

I haven't looked into the actual code yet but hope that is a good starting point.

Cheers

**Comment by dsymonds** [comment]
This sounds like it is an upstream bug in the `gcimporter15` package.

@griesemer @alandonovan

**Comment by griesemer** [comment]
Yes, working on this right now.

**Comment by griesemer** [comment]
Work in progress: https://go-review.googlesource.com/22963 .

**Comment by wolfeidau** [comment]
Thanks a lot for following up on this.

**Comment by griesemer** [comment]
@wolfeidau A fix has been pushed and addresses the issue in x/tools. It expect it to address the golint issue (note that all packages need to be compiled/installed with the latest compiler version). Perhaps you can verify it's fixed and close this if so. Thanks.

**Comment by wolfeidau** [comment]
@griesemer I pulled down master of x/tools on my machine and rebuilt `golint` and it is now fixed.

Cheers
