### ISSUE TITLE
panic: (symbol) already declared

### ISSUE THREAD

**Issue by calmh** [golang/lint#223]
```
jb@syno:~/s/g/s/syncthing $ go version
go version go1.7beta2 darwin/amd64

jb@syno:~/s/g/s/syncthing $ golint ./lib/...
lib/auto/gui.files.go:8:2: exported const AssetsBuildDate should have comment (or a comment on this block) or be unexported
lib/auto/gui.files.go:11:1: exported function Assets should have comment or be unexported
panic: ErrWrongSupervisor already declared [recovered]
	panic: ErrWrongSupervisor already declared

goroutine 1 [running]:
panic(0x2029a0, 0xc4202a9a70)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
go/types.(*Checker).handleBailout(0xc4200881c0, 0xc42073b5e0)
	/usr/local/go/src/go/types/check.go:213 +0xae
panic(0x2029a0, 0xc4202a9a70)
	/usr/local/go/src/runtime/panic.go:458 +0x243
golang.org/x/tools/go/gcimporter15.(*importer).declare(0xc4201260d0, 0x33e220, 0xc42031c460)
	/Users/jb/src/golang.org/x/tools/go/gcimporter15/bimport.go:182 +0x16b
golang.org/x/tools/go/gcimporter15.(*importer).obj(0xc4201260d0, 0xfffffffffffffffc)
	/Users/jb/src/golang.org/x/tools/go/gcimporter15/bimport.go:202 +0x1bd
golang.org/x/tools/go/gcimporter15.BImportData(0xc4204c3300, 0xc4201c1a70, 0xc4201ce000, 0x14cbc, 0x1fe00, 0xc4201aea61, 0x19, 0x3f, 0xd184, 0x22f440, ...)
	/Users/jb/src/golang.org/x/tools/go/gcimporter15/bimport.go:95 +0x3a8
golang.org/x/tools/go/gcimporter15.Import(0xc4201c1a70, 0xc4201aea61, 0x19, 0xc42019cd20, 0xa, 0x0, 0x0, 0x0)
	/Users/jb/src/golang.org/x/tools/go/gcimporter15/gcimporter.go:178 +0x5da
github.com/golang/lint.importer.ImportFrom(0x26ab78, 0xc4201c1a70, 0xc4201aea61, 0x19, 0xc42019cd20, 0xa, 0x0, 0x228460, 0x1, 0x42cdb8)
	/Users/jb/src/github.com/golang/lint/lint16.go:16 +0x58
github.com/golang/lint.(*importer).ImportFrom(0xc42017c060, 0xc4201aea61, 0x19, 0xc42019cd20, 0xa, 0x0, 0xc42025f810, 0x0, 0x0)
	<autogenerated>:5 +0x97
go/types.(*Checker).collectObjects(0xc4200881c0)
	/usr/local/go/src/go/types/resolver.go:191 +0x81d
go/types.(*Checker).checkFiles(0xc4200881c0, 0xc4201c71c0, 0x6, 0x8, 0x0, 0x0)
	/usr/local/go/src/go/types/check.go:225 +0xaa
go/types.(*Checker).Files(0xc4200881c0, 0xc4201c71c0, 0x6, 0x8, 0xc4201c1b60, 0xc420259748)
	/usr/local/go/src/go/types/check.go:218 +0x49
go/types.(*Config).Check(0xc4201c7180, 0xc420219ff8, 0x6, 0xc4201878c0, 0xc4201c71c0, 0x6, 0x8, 0xc4201bd180, 0xc4201c8340, 0x18, ...)
	/usr/local/go/src/go/types/api.go:344 +0x19f
github.com/golang/lint.(*pkg).typeCheck(0xc4203279f0, 0x60000000004f410, 0x8)
	/Users/jb/src/github.com/golang/lint/lint.go:274 +0x403
github.com/golang/lint.(*pkg).lint(0xc4203279f0, 0xc4201a2150, 0xc420259918, 0xc420259910)
	/Users/jb/src/github.com/golang/lint/lint.go:130 +0x40
github.com/golang/lint.(*Linter).LintFiles(0xc42073ba40, 0xc42073bae0, 0xc420259aa8, 0xc420259ab8, 0x554, 0x0, 0x0)
	/Users/jb/src/github.com/golang/lint/lint.go:110 +0x6e7
main.lintFiles(0xc4200a2500, 0x6, 0xa)
	/Users/jb/src/github.com/golang/lint/golint/golint.go:92 +0x234
main.lintImportedPackage(0xc42000d880, 0x0, 0x0)
	/Users/jb/src/github.com/golang/lint/golint/golint.go:136 +0x364
main.lintDir(0xc42000f7a0, 0xc)
	/Users/jb/src/github.com/golang/lint/golint/golint.go:107 +0x60
main.main()
	/Users/jb/src/github.com/golang/lint/golint/golint.go:49 +0x389

jb@syno:~/s/g/s/syncthing $ cd ~/src/github.com/golang/lint/
jb@syno:~/s/g/g/lint $ git describe --always
c7bacac
```

Code being checked is current `master` of github.com/syncthing/syncthing.

**Comment by petemoore** [comment]
I think I have the same problem...

```
pmoore@Petes-iMac:~ $ golint github.com/taskcluster/taskcluster-worker/engines/osxnative
panic: ErrorKey already declared [recovered]
	panic: ErrorKey already declared

goroutine 1 [running]:
panic(0x203cc0, 0xc4206f4070)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
go/types.(*Checker).handleBailout(0xc42015c000, 0xc4203735e0)
	/usr/local/go/src/go/types/check.go:213 +0xae
panic(0x203cc0, 0xc4206f4070)
	/usr/local/go/src/runtime/panic.go:458 +0x243
github.com/taskcluster/taskcluster-worker/vendor/golang.org/x/tools/go/gcimporter15.(*importer).declare(0xc42015c0e0, 0x342400, 0xc420364000)
	/Users/pmoore/go/src/github.com/taskcluster/taskcluster-worker/vendor/golang.org/x/tools/go/gcimporter15/bimport.go:184 +0x16b
github.com/taskcluster/taskcluster-worker/vendor/golang.org/x/tools/go/gcimporter15.(*importer).obj(0xc42015c0e0, 0xfffffffffffffffc)
	/Users/pmoore/go/src/github.com/taskcluster/taskcluster-worker/vendor/golang.org/x/tools/go/gcimporter15/bimport.go:204 +0x1c5
github.com/taskcluster/taskcluster-worker/vendor/golang.org/x/tools/go/gcimporter15.BImportData(0xc420010680, 0xc420156cf0, 0xc4205de000, 0x22cf3, 0x3fe00, 0xc4201443c1, 0x1a, 0x4b, 0xd1a4, 0x2307c0, ...)
	/Users/pmoore/go/src/github.com/taskcluster/taskcluster-worker/vendor/golang.org/x/tools/go/gcimporter15/bimport.go:97 +0x3e8
github.com/taskcluster/taskcluster-worker/vendor/golang.org/x/tools/go/gcimporter15.Import(0xc420156cf0, 0xc4201443c1, 0x1a, 0xc4200e0780, 0x50, 0xc4203e5ae0, 0x0, 0x0)
	/Users/pmoore/go/src/github.com/taskcluster/taskcluster-worker/vendor/golang.org/x/tools/go/gcimporter15/gcimporter.go:178 +0x5da
github.com/taskcluster/taskcluster-worker/vendor/github.com/golang/lint.importer.ImportFrom(0x26bfc8, 0xc420156cf0, 0xc4201443c1, 0x1a, 0xc4200e0780, 0x50, 0x0, 0x2297e0, 0x76589b01, 0x4610f0)
	/Users/pmoore/go/src/github.com/taskcluster/taskcluster-worker/vendor/github.com/golang/lint/lint16.go:16 +0x58
github.com/taskcluster/taskcluster-worker/vendor/github.com/golang/lint.(*importer).ImportFrom(0xc4201517f0, 0xc4201443c1, 0x1a, 0xc4200e0780, 0x50, 0x0, 0xc42022eaf0, 0x0, 0x0)
	<autogenerated>:5 +0x97
go/types.(*Checker).collectObjects(0xc42015c000)
	/usr/local/go/src/go/types/resolver.go:191 +0x826
go/types.(*Checker).checkFiles(0xc42015c000, 0xc420148c00, 0xe, 0x10, 0x0, 0x0)
	/usr/local/go/src/go/types/check.go:225 +0xaa
go/types.(*Checker).Files(0xc42015c000, 0xc420148c00, 0xe, 0x10, 0xc420156de0, 0xc420103738)
	/usr/local/go/src/go/types/check.go:218 +0x49
go/types.(*Config).Check(0xc420158cc0, 0xc4201503d7, 0x9, 0xc420011c00, 0xc420148c00, 0xe, 0x10, 0xc420152cd0, 0xc420087770, 0xc420087658, ...)
	/usr/local/go/src/go/types/api.go:344 +0x1a3
github.com/taskcluster/taskcluster-worker/vendor/github.com/golang/lint.(*pkg).typeCheck(0xc420015e00, 0x2d0000000004f610, 0x8)
	/Users/pmoore/go/src/github.com/taskcluster/taskcluster-worker/vendor/github.com/golang/lint/lint.go:274 +0x40a
github.com/taskcluster/taskcluster-worker/vendor/github.com/golang/lint.(*pkg).lint(0xc420015e00, 0xc4200de540, 0xc420103908, 0xc420103900)
	/Users/pmoore/go/src/github.com/taskcluster/taskcluster-worker/vendor/github.com/golang/lint/lint.go:130 +0x40
github.com/taskcluster/taskcluster-worker/vendor/github.com/golang/lint.(*Linter).LintFiles(0xc420373a40, 0xc420373ae0, 0xc42003faa8, 0xc42003fab8, 0x5a4, 0x0, 0x0)
	/Users/pmoore/go/src/github.com/taskcluster/taskcluster-worker/vendor/github.com/golang/lint/lint.go:110 +0x6ef
main.lintFiles(0xc4200b7400, 0xe, 0x14)
	/Users/pmoore/go/src/github.com/taskcluster/taskcluster-worker/vendor/github.com/golang/lint/golint/golint.go:92 +0x23c
main.lintImportedPackage(0xc420087180, 0x0, 0x0)
	/Users/pmoore/go/src/github.com/taskcluster/taskcluster-worker/vendor/github.com/golang/lint/golint/golint.go:136 +0x364
main.lintPackage(0x7fff5fbff8ef, 0x3b)
	/Users/pmoore/go/src/github.com/taskcluster/taskcluster-worker/vendor/github.com/golang/lint/golint/golint.go:112 +0x75
main.main()
	/Users/pmoore/go/src/github.com/taskcluster/taskcluster-worker/vendor/github.com/golang/lint/golint/golint.go:57 +0x1c1
```

**Comment by petemoore** [comment]
Ah ... I wonder if this is due to vendor dependencies... Will check.

**Comment by petemoore** [comment]
@calmh I suspect it is related to `/Users/jb/src/golang.org/x/tools/go/gcimporter15` which (I'm guessing) is probably go 1.5 related. Maybe a `go get -u github.com/golang/lint` would fix this for you - I'm guessing there are changes added to handle go 1.7.

**Comment by dominikh** [comment]
You will need to wipe/repopulate your GOPATH/pkg directory. This issue in particular can occur when you tested release candidates of Go 1.7 that produced slightly wrong export data, which trips up the importer.

**Comment by calmh** [comment]
This is no longer an issue for me in current golint and Go 1.7. Thanks all!

**Comment by petemoore** [comment]
Thanks @dominikh. I also fixed my problem by updating golint and its dependencies, which were vendored on an older version. Whoops! :smile:

**Comment by dsnet** [comment]
Thanks @dominikh for your suggestion.
