### ISSUE TITLE
go-lint panic

### ISSUE THREAD

**Issue by alimoeeny** [golang/lint#250]
Using emacs (spacemacs), when saving files, often (like %10 of times, but cann't figure out a pattern), I get this:

```

Saving file /Users/ali/MYPROJPATH/src/github.com/COMP/PROJ/PACKAGE/FLUser.go...
Wrote /var/folders/f9/b6xfd7d57rd6vnlmck35pxwm0000gn/T/gofmt64451Ici.go
Calling gofmt: goimports (-srcdir /Users/ali/MYPROJPATH/src/github.com/COMP/PROJ/PACKAGE/ -w /var/folders/f9/b6xfd7d57rd6vnlmck35pxwm0000gn/T/gofmt64451Ici.go)
Buffer is already gofmted
Wrote /Users/ali/MYPROJPATH/src/github.com/COMP/PROJ/PACKAGE/FLUser.go
Suspicious state from syntax checker go-golint: Flycheck checker go-golint returned non-zero exit code 2, but its output contained no errors: panic: runtime error: index out of range [recovered]
	panic: runtime error: index out of range

goroutine 1 [running]:
panic(0x2b8ae0, 0xc82000e070)
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/panic.go:464 +0x3e6
go/types.(*Checker).handleBailout(0xc8200d2000, 0xc8200e5538)
	/usr/local/Cellar/go/1.6.1/libexec/src/go/types/check.go:213 +0xd8
panic(0x2b8ae0, 0xc82000e070)
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/panic.go:426 +0x4e9
golang.org/x/tools/go/gcimporter15.(*importer).string(0xc820114000, 0x0, 0x0)
	/Users/ali/src/golang.org/x/tools/go/gcimporter15/bimport.go:625 +0xc2
golang.org/x/tools/go/gcimporter15.BImportData(0xc820079dd0, 0xc820104000, 0x8d3d, 0xfe00, 0xc82006e641, 0x1a, 0x0, 0x1a, 0x0, 0x0)
	/Users/ali/src/golang.org/x/tools/go/gcimporter15/bimport.go:70 +0x18b
golang.org/x/tools/go/gcimporter15.Import(0xc820079dd0, 0xc82006e641, 0x1a, 0x7fff5fbffbee, 0x41, 0x0, 0x0, 0x0)
	/Users/ali/src/golang.org/x/tools/go/gcimporter15/gcimporter.go:177 +0x744
github.com/golang/lint.importer.ImportFrom(0x38a630, 0xc820079dd0, 0xc82006e641, 0x1a, 0x7fff5fbffbee, 0x41, 0x0, 0x2d6100, 0x0, 0x0)
	/Users/ali/src/github.com/golang/lint/lint16.go:16 +0x60
github.com/golang/lint.(*importer).ImportFrom(0xc820075980, 0xc82006e641, 0x1a, 0x7fff5fbffbee, 0x41, 0x0, 0x2, 0x0, 0x0)
	<autogenerated>:5 +0xdf
go/types.(*Checker).collectObjects(0xc8200d2000)
	/usr/local/Cellar/go/1.6.1/libexec/src/go/types/resolver.go:191 +0x311f
go/types.(*Checker).Files(0xc8200d2000, 0xc820080190, 0x1, 0x1, 0x0, 0x0)
	/usr/local/Cellar/go/1.6.1/libexec/src/go/types/check.go:223 +0xb3
go/types.(*Config).Check(0xc820071cc0, 0xc8200747a0, 0x6, 0xc8200705c0, 0xc820080190, 0x1, 0x1, 0xc8200d02d0, 0xc8200cec20, 0x0, ...)
	/usr/local/Cellar/go/1.6.1/libexec/src/go/types/api.go:344 +0x1f7
github.com/golang/lint.(*pkg).typeCheck(0xc8200835e0, 0x0, 0x0)
	/Users/ali/src/github.com/golang/lint/lint.go:274 +0x494
github.com/golang/lint.(*pkg).lint(0xc8200835e0, 0x0, 0x0, 0x0)
	/Users/ali/src/github.com/golang/lint/lint.go:130 +0x4a
github.com/golang/lint.(*Linter).LintFiles(0xc8200e59e0, 0xc8200e5b50, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/ali/src/github.com/golang/lint/lint.go:110 +0x4c9
main.lintFiles(0xc8200e5ea0, 0x1, 0x1)
	/Users/ali/src/github.com/golang/lint/golint/golint.go:83 +0x2ca
main.main()
	/Users/ali/src/github.com/golang/lint/golint/golint.go:50 +0x3a4

Try installing a more recent version of go-golint, and please open a bug report if the issue persists in the latest release.  Thanks!

```

**Comment by dsnet** [comment]
What version of `lint` is this? The presence of a "lin16.go" file indicates that this is an older revision. Can you upgrade to tip and see if the panic still occurs?

**Comment by alimoeeny** [comment]
Thanks @dsnet  
I was under the impression that I am on `tip` because the error itself suggests updating.
It is very possible that my editor was using a different `GOPATH` 
I cannot confirm for sure since I changed a few things at the same time without checking step by step. I am closing this issue, will open if could confirm it happens on on `tip`
