### ISSUE TITLE
Save command always raises this error at every execution

### ISSUE THREAD

**Issue by chawlanikhil24** [golang/lint#273]
Error: spawn golint ENOENT
    at exports._errnoException (util.js:1026:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by dsnet** [comment]
I don't think this is an error related to the `golint` program. Given that the stacktrace is for javascript, it seems that some other program written in JS is having trouble locating the `golint` binary (hence the ENOENT error). This seems to be an issue in that JS code and the environment that it is trying to invoke `golint` in.
