### ISSUE TITLE
panic when go version is upgraded to 1.11

### ISSUE THREAD

**Issue by cwen0** [golang/lint#411]
1. What version of Go are you using (go version)? 
```
go version go1.11 linux/amd64
``` 
2. What operating system and processor architecture are you using (go env)?
```
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/root/dev/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build340191869=/tmp/go-build -gno-record-gcc-switches"
```
3. What did you do? 

I upgraded the go version from 1.10 to 1.11 and after running `go get -u  github.com/golang/lint/golint` , panic will occur when running golint

```
panic: assertion failed [recovered]
	panic: assertion failed

goroutine 1 [running]:
go/types.(*Checker).handleBailout(0xc002396a50, 0xc001815628)
	/usr/local/go/src/go/types/check.go:236 +0x98
panic(0x618d20, 0x6a9fd0)
	/usr/local/go/src/runtime/panic.go:513 +0x1b9
go/types.assert(...)
	/usr/local/go/src/go/types/errors.go:18
go/types.(*Checker).recordTypeAndValue(0xc002396a50, 0x0, 0x0, 0x3, 0x6ad300, 0xc004bdab00, 0x0, 0x0)
	/usr/local/go/src/go/types/check.go:281 +0x279
go/types.(*Checker).exprInternal(0xc002396a50, 0xc004c6c040, 0x6add40, 0xc000f32500, 0x6ad300, 0xc004bdab00, 0x40b33f)
	/usr/local/go/src/go/types/expr.go:1164 +0x17c4
go/types.(*Checker).rawExpr(0xc002396a50, 0xc004c6c040, 0x6add40, 0xc000f32500, 0x6ad300, 0xc004bdab00, 0x40bbc8)
	/usr/local/go/src/go/types/expr.go:969 +0x81
go/types.(*Checker).exprWithHint(0xc002396a50, 0xc004c6c040, 0x6add40, 0xc000f32500, 0x6ad300, 0xc004bdab00)
	/usr/local/go/src/go/types/expr.go:1597 +0x73
go/types.(*Checker).indexedElts(0xc002396a50, 0xc001516600, 0x6, 0x8, 0x6ad300, 0xc004bdab00, 0xffffffffffffffff, 0x6ad500)
	/usr/local/go/src/go/types/expr.go:939 +0x1e2
go/types.(*Checker).exprInternal(0xc002396a50, 0xc001dcff40, 0x6add40, 0xc000f327c0, 0x0, 0x0, 0x6ad340)
	/usr/local/go/src/go/types/expr.go:1174 +0xd7a
go/types.(*Checker).rawExpr(0xc002396a50, 0xc001dcff40, 0x6add40, 0xc000f327c0, 0x0, 0x0, 0x0)
	/usr/local/go/src/go/types/expr.go:969 +0x81
go/types.(*Checker).multiExpr(0xc002396a50, 0xc001dcff40, 0x6add40, 0xc000f327c0)
	/usr/local/go/src/go/types/expr.go:1575 +0x58
go/types.(*Checker).expr(0xc002396a50, 0xc001dcff40, 0x6add40, 0xc000f327c0)
	/usr/local/go/src/go/types/expr.go:1569 +0x49
go/types.(*Checker).varDecl(0xc002396a50, 0xc004c572c0, 0xc004da3ae8, 0x1, 0x1, 0x0, 0x0, 0x6add40, 0xc000f327c0)
	/usr/local/go/src/go/types/decl.go:425 +0x1b7
go/types.(*Checker).objDecl(0xc002396a50, 0x6afea0, 0xc004c572c0, 0x0, 0xc001815528, 0x0, 0x8)
	/usr/local/go/src/go/types/decl.go:244 +0x83c
go/types.(*Checker).packageObjects(0xc002396a50)
	/usr/local/go/src/go/types/resolver.go:542 +0x26f
go/types.(*Checker).checkFiles(0xc002396a50, 0xc000f47c20, 0x3, 0x4, 0x0, 0x0)
	/usr/local/go/src/go/types/check.go:250 +0xa5
go/types.(*Checker).Files(0xc002396a50, 0xc000f47c20, 0x3, 0x4, 0xc000f50000, 0xc001523008)
	/usr/local/go/src/go/types/check.go:241 +0x49
go/types.(*Config).Check(0xc000f45040, 0xc0015275a0, 0x4, 0xc001542e40, 0xc000f47c20, 0x3, 0x4, 0xc000f39f40, 0x0, 0x4d, ...)
	/usr/local/go/src/go/types/api.go:351 +0x11a
golang.org/x/lint.(*pkg).typeCheck(0xc001546410, 0x1000, 0xc000f4e000)
	/root/dev/go/src/golang.org/x/lint/lint.go:283 +0x313
golang.org/x/lint.(*pkg).lint(0xc001546410, 0xbfd, 0xdfd, 0x1)
	/root/dev/go/src/golang.org/x/lint/lint.go:153 +0x40
golang.org/x/lint.(*Linter).LintFiles(0xc001815a60, 0xc001815ae8, 0xc0001ed8c0, 0x38, 0xc001815d00, 0x0, 0x0)
	/root/dev/go/src/golang.org/x/lint/lint.go:115 +0x634
main.lintFiles(0xc0015463c0, 0x5, 0x5)
	/root/dev/go/src/github.com/golang/lint/golint/golint.go:114 +0x1bd
main.lintImportedPackage(0xc001caa700, 0x0, 0x0)
	/root/dev/go/src/github.com/golang/lint/golint/golint.go:158 +0x30b
main.lintDir(0xc0000dd0b0, 0x2f)
	/root/dev/go/src/github.com/golang/lint/golint/golint.go:129 +0x60
main.main()
	/root/dev/go/src/github.com/golang/lint/golint/golint.go:75 +0x25d
```

**Comment by randall77** [comment]
I found a small reproducer:
```
package main

var x = [][n]int{
	0: {},
}
```
Note that the error depends on `n` being undefined.
```
$ golint foo.go 
panic: assertion failed [recovered]
	panic: assertion failed

goroutine 1 [running]:
go/types.(*Checker).handleBailout(0xc0000e8000, 0xc0000f1728)
	/Users/khr/go1.11/src/go/types/check.go:236 +0x98
panic(0x1215c00, 0x12a6240)
	/Users/khr/go1.11/src/runtime/panic.go:513 +0x1b9
go/types.assert(...)
	/Users/khr/go1.11/src/go/types/errors.go:18
go/types.(*Checker).recordTypeAndValue(0xc0000e8000, 0x0, 0x0, 0x3, 0x12a9580, 0xc0000883a0, 0x0, 0x0)
	/Users/khr/go1.11/src/go/types/check.go:281 +0x279
go/types.(*Checker).exprInternal(0xc0000e8000, 0xc0000705c0, 0x12a9fc0, 0xc000070340, 0x12a9580, 0xc0000883a0, 0x100b16f)
	/Users/khr/go1.11/src/go/types/expr.go:1164 +0x17c4
go/types.(*Checker).rawExpr(0xc0000e8000, 0xc0000705c0, 0x12a9fc0, 0xc000070340, 0x12a9580, 0xc0000883a0, 0x100b9f8)
	/Users/khr/go1.11/src/go/types/expr.go:969 +0x81
go/types.(*Checker).exprWithHint(0xc0000e8000, 0xc0000705c0, 0x12a9fc0, 0xc000070340, 0x12a9580, 0xc0000883a0)
	/Users/khr/go1.11/src/go/types/expr.go:1597 +0x73
go/types.(*Checker).indexedElts(0xc0000e8000, 0xc000090380, 0x1, 0x1, 0x12a9580, 0xc0000883a0, 0xffffffffffffffff, 0x12a9780)
	/Users/khr/go1.11/src/go/types/expr.go:939 +0x1e2
go/types.(*Checker).exprInternal(0xc0000e8000, 0xc000070480, 0x12a9fc0, 0xc000070380, 0x0, 0x0, 0x100ac65)
	/Users/khr/go1.11/src/go/types/expr.go:1174 +0xd7a
go/types.(*Checker).rawExpr(0xc0000e8000, 0xc000070480, 0x12a9fc0, 0xc000070380, 0x0, 0x0, 0x0)
	/Users/khr/go1.11/src/go/types/expr.go:969 +0x81
go/types.(*Checker).multiExpr(0xc0000e8000, 0xc000070480, 0x12a9fc0, 0xc000070380)
	/Users/khr/go1.11/src/go/types/expr.go:1575 +0x58
go/types.(*Checker).expr(0xc0000e8000, 0xc000070480, 0x12a9fc0, 0xc000070380)
	/Users/khr/go1.11/src/go/types/expr.go:1569 +0x49
go/types.(*Checker).varDecl(0xc0000e8000, 0xc0000b97c0, 0xc0000840a8, 0x1, 0x1, 0x0, 0x0, 0x12a9fc0, 0xc000070380)
	/Users/khr/go1.11/src/go/types/decl.go:425 +0x1b7
go/types.(*Checker).objDecl(0xc0000e8000, 0x12ac0e0, 0xc0000b97c0, 0x0, 0xc0000bf628, 0x0, 0x8)
	/Users/khr/go1.11/src/go/types/decl.go:244 +0x83c
go/types.(*Checker).packageObjects(0xc0000e8000)
	/Users/khr/go1.11/src/go/types/resolver.go:542 +0x26f
go/types.(*Checker).checkFiles(0xc0000e8000, 0xc000084090, 0x1, 0x1, 0x0, 0x0)
	/Users/khr/go1.11/src/go/types/check.go:250 +0xa5
go/types.(*Checker).Files(0xc0000e8000, 0xc000084090, 0x1, 0x1, 0xc0000b9720, 0x1426d70)
	/Users/khr/go1.11/src/go/types/check.go:241 +0x49
go/types.(*Config).Check(0xc000070440, 0xc000082398, 0x4, 0xc000070300, 0xc000084090, 0x1, 0x1, 0xc0000b9680, 0x10d768e, 0x0, ...)
	/Users/khr/go1.11/src/go/types/api.go:351 +0x11a
golang.org/x/lint.(*pkg).typeCheck(0xc0000b9590, 0x100b9f8, 0xd0)
	/Users/khr/gopath/src/golang.org/x/lint/lint.go:283 +0x313
golang.org/x/lint.(*pkg).lint(0xc0000b9590, 0xc00007ab10, 0x7fff5fbffc77, 0x6)
	/Users/khr/gopath/src/golang.org/x/lint/lint.go:153 +0x40
golang.org/x/lint.(*Linter).LintFiles(0xc0000bfb60, 0xc0000bfbe8, 0x7fff5fbffc77, 0x6, 0xc0000bfda0, 0x0, 0x0)
	/Users/khr/gopath/src/golang.org/x/lint/lint.go:115 +0x634
main.lintFiles(0xc000090340, 0x1, 0x1)
	/Users/khr/gopath/src/github.com/golang/lint/golint/golint.go:114 +0x1bd
main.main()
	/Users/khr/gopath/src/github.com/golang/lint/golint/golint.go:78 +0x3eb
```
(Found a bad case by linting my whole gopath. Error is reduced from the file golang.org/x/text/internal/export/idna/idna10.0.0.go.)

**Comment by randall77** [comment]
@griesemer

**Comment by griesemer** [comment]
This is clearly a go/types bug.

**Comment by griesemer** [comment]
Pending fix: https://go-review.googlesource.com/c/go/+/133415 .

**Comment by griesemer** [comment]
@cwen0 Not sure what the policy is for lint issues. But this bug has been fixed in the golang master branch (in go/types) and thus should not appear anymore in lint using the latest go/types. Please feel free to close.

**Comment by cwen0** [comment]
@griesemer thanks, I will close this issue.
